-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Events Table
CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    venue VARCHAR(100),
    artist VARCHAR(100),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    capacity INTEGER NOT NULL,
    rows_count INTEGER NOT NULL,
    seats_per_row INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seats Table
CREATE TABLE IF NOT EXISTS seats (
    id SERIAL PRIMARY KEY,
    event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
    row_label VARCHAR(5) NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_label VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'SOLD', 'RESERVED')),
    UNIQUE(event_id, seat_label)
);

-- Tickets Table
CREATE TABLE IF NOT EXISTS tickets (
    id SERIAL PRIMARY KEY,
    seat_id INTEGER UNIQUE REFERENCES seats(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    user_name VARCHAR(100), -- For guest checkout or display
    status VARCHAR(20) DEFAULT 'VALID' CHECK (status IN ('VALID', 'USED', 'EXPIRED', 'CANCELLED')),
    qr_code TEXT,
    purchase_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    blockchain_hash TEXT
);

-- Blockchain Logs (Simulated)
CREATE TABLE IF NOT EXISTS blockchain_logs (
    id SERIAL PRIMARY KEY,
    ticket_id INTEGER REFERENCES tickets(id),
    action VARCHAR(50) NOT NULL, -- CREATED, SOLD, USED, CANCELLED
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    previous_hash TEXT,
    hash TEXT NOT NULL
);

-- Initial Admin User (password: admin123)
INSERT INTO users (username, password, role) 
VALUES ('admin', '$2a$10$Xm77Z9V.X.Vp.7q5z0jU.O9z8gZ7bO3.j7Q1z8Q7j7Q1z8Q7j7Q1z', 'ADMIN')
ON CONFLICT (username) DO NOTHING;

-- Seed Data: International Music Festival Events
INSERT INTO events (name, artist, venue, start_time, end_time, capacity, rows_count, seats_per_row) VALUES
('Global Beats Festival - Day 1', 'Daft Punk & Phoenix', 'Olympic Stadium', '2026-07-15 18:00:00+00', '2026-07-15 23:59:00+00', 100, 10, 10),
('Stellar Jazz Night', 'Kamasi Washington', 'Royal Opera House', '2026-07-16 20:00:00+00', '2026-07-16 23:00:00+00', 50, 5, 10),
('Techno Sunrise', 'Charlotte de Witte', 'The Underground Warehouse', '2026-07-17 22:00:00+00', '2026-07-18 06:00:00+00', 100, 10, 10);

-- Note: In a real app, seats would be generated by a trigger or service. 
-- For this seed, we initialize seats for the first event
DO $$
DECLARE
    r RECORD;
    row_idx INTEGER;
    seat_idx INTEGER;
BEGIN
    FOR r IN SELECT id, rows_count, seats_per_row FROM events LOOP
        FOR row_idx IN 1..r.rows_count LOOP
            FOR seat_idx IN 1..r.seats_per_row LOOP
                INSERT INTO seats (event_id, row_label, seat_number, seat_label)
                VALUES (r.id, CHR(64 + row_idx), seat_idx, CHR(64 + row_idx) || seat_idx)
                ON CONFLICT DO NOTHING;
            END LOOP;
        END LOOP;
    END LOOP;
END $$;
